#name: trackfactor
#description: A comprehensive Flutter fitness tracking application combining workout tracking, nutrition logging, and step counting with beautiful animations.
#publish_to: 'none'
#version: 1.0.0+1
#
#environment:
#  sdk: '>=3.0.0 <4.0.0'
#
#dependencies:
#  flutter:
#    sdk: flutter
#
#  # State Management
#  flutter_bloc: ^8.1.3
#  equatable: ^2.0.5
#  hydrated_bloc: ^9.1.2
#
#  # Local Storage
#  hive: ^2.2.3
#  hive_flutter: ^1.1.0
#  path_provider: ^2.1.2
#  shared_preferences: ^2.2.2
#
#  # HTTP and API Integration
#  dio: ^5.3.3
#  http: ^1.1.0
#
#  # Health and Fitness
#  health: ^10.2.0
#  pedometer: ^4.1.1
#
#  # Charts and Visualization
#  fl_chart: ^0.66.0
#
#  # UI, Animations, and Images
#  animations: ^2.0.8
#  lottie: ^2.7.0
#  staggered_animated_widget: ^2.0.4
#  cached_network_image: ^3.3.1
#
#  # Utilities
#  permission_handler: ^11.1.0
#  intl: ^0.19.0
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  flutter_lints: ^3.0.1
#  hive_generator: ^2.0.1
#  build_runner: ^2.4.7
#
#flutter:
#  uses-material-design: true
#  assets:
#    - assets/lottie/
#    - .env
name: trackfactor
description: A comprehensive Flutter fitness tracking application combining workout tracking, nutrition logging, and step counting with beautiful animations.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  hydrated_bloc: ^9.1.2

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2

  # HTTP and API Integration
  dio: ^5.3.3
  http: ^1.1.0

  # Environment Variables
  flutter_dotenv: ^5.1.0  # ✅ Add this line

  # Health and Fitness
  health: ^10.2.0
  pedometer: ^4.1.1

  # Charts and Visualization
  fl_chart: ^0.66.0

  # UI, Animations, and Images
  animations: ^2.0.8
  lottie: ^2.7.0
  cached_network_image: ^3.3.1

  # Utilities
  permission_handler: ^11.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - .env  # ✅ Add this line to include .env file as asset
    - assets/lottie/
